spring:
  profiles:
    active: dev  # dev 환경

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/data-jpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:  # 페이징 처리 기본값 전역 설정
        default-page-size: 10
        max-page-size: 10

logging:
  level:
    org:
      hibernate.SQL: debug
