spring:
  profiles:
    active: dev  # dev 환경

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        use_sql_comments: true  # QueryDSL log 출력

logging:
  level:
    org:
      hibernate.SQL: debug
#      hibernate.type: true
